/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class CambiarUser extends javax.swing.JFrame {

    public Administrador admin;
    public Principal ventanaPrincipal;

    /**
     * Creates new form CambiarUser
     */
    public CambiarUser(Principal ventanaPrinci) {
        initComponents();
        admin = new Administrador();
        this.ventanaPrincipal = ventanaPrinci;
        this.setTitle("Cambiar Usuario de la Base de Datos");
        this.setSize(400, 250);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private CambiarUser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUser = new javax.swing.JTextField();
        txtPassUser = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCambioUser.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 10, 70, 70);

        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(103, 168, 90, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(199, 168, 90, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Cambio Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 159, 30);

        jLabel2.setText("Nombre de Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 99, 150, 14);

        jLabel3.setText("Contrasena de Usuario:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 133, 160, 14);
        getContentPane().add(txtNombreUser);
        txtNombreUser.setBounds(190, 90, 170, 30);
        getContentPane().add(txtPassUser);
        txtPassUser.setBounds(190, 120, 170, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoFor.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 410, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if ((txtNombreUser.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Nombre de Usuario obligatoriamente");
        } else if ((txtPassUser.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una Contrasena de Usuario obligatoriamente");
        } else {
            Object obj;
            obj = admin.cambiarUser(txtNombreUser.getText(), txtPassUser.getText());
            System.out.println("2" + obj);
            if (obj != null) {
                JOptionPane.showMessageDialog(null, "Cambio de usuario correctamente");
                this.setVisible(false);
                ventanaPrincipal.actualizarUser();
                ventanaPrincipal.verificarBotones();
            }else{
                JOptionPane.showMessageDialog(null, "Error al Conectarse a la Base de Datos, nombre o Contrasena incorrecta");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNombreUser;
    private javax.swing.JPasswordField txtPassUser;
    // End of variables declaration//GEN-END:variables
}
