/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class EditarPersona extends javax.swing.JFrame {

    public String clave;
    public String nombreTabla;
    public Config_Persona ventanaTabla;
    public Administrador admin;
    public ArrayList datosCampos;

    /**
     * Creates new form EditarPersona
     */
    public EditarPersona(String clav, String nombreT, Config_Persona ventana) {
        initComponents();

        admin = new Administrador();
        this.clave = clav;
        this.nombreTabla = nombreT;
        this.ventanaTabla = ventana;
        inicializar();
        txtID.setEnabled(false);
        this.setTitle("Editar Registro de la Tabla Persona");
        this.setSize(430, 370);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        verificar();
    }

    public void verificar() {
        if (this.txtID.getText().isEmpty()) {
            this.setVisible(false);
        }
    }

    private EditarPersona() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void inicializar() {
        ArrayList datos = new ArrayList<>();
        datos = admin.recuperarDatos(clave, nombreTabla);
        if (datos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID INCOORECTONo existen datos recuperados");
            //this.setVisible(false);
        } else {
            //if(datos==null){
//                JOptionPane.showMessageDialog(null, "No existen datos decuperados");
            //          }else{
            txtID.setText((datos.get(0)).toString());
            txtNombre.setText((datos.get(1)).toString());
            txtApellido.setText((datos.get(2)).toString());
            txtDireccion.setText((datos.get(3)).toString());
            txtTelefono.setText((datos.get(4)).toString());
            txtFechaN.setText((datos.get(5)).toString());
            this.setVisible(true);
//            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFechaN = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        brnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(null);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(157, 141, 224, 30);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(157, 179, 224, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(157, 211, 224, 30);
        getContentPane().add(txtFechaN);
        txtFechaN.setBounds(157, 249, 224, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(119, 295, 91, 23);

        brnCancelar.setText("Cancelar");
        brnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(brnCancelar);
        brnCancelar.setBounds(236, 295, 82, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Editar Registro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 143, 32);

        jLabel2.setText("ID Persona:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 68, 90, 14);

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 106, 90, 14);

        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 144, 80, 14);

        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(62, 182, 90, 14);

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(62, 217, 90, 14);

        jLabel7.setText("Fecha Nacimiento: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(62, 252, 120, 14);
        getContentPane().add(txtID);
        txtID.setBounds(157, 65, 224, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(157, 103, 224, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoFor.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 440, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //datosCampos = new ArrayList<>();
        String[] datos = new String[6];
        String id = txtID.getText();
        //datosCampos.add(id);
        datos[0] = id;
        String nomb = txtNombre.getText();
        //datosCampos.add(nomb);
        datos[1] = nomb;
        String ape = txtApellido.getText();
        //datosCampos.add(ape);
        datos[2] = ape;
        String direc = txtDireccion.getText();
        //datosCampos.add(direc);
        datos[3] = direc;
        String fech = txtTelefono.getText();
        //datosCampos.add(fech);
        datos[4] = fech;
        String telf = txtFechaN.getText();
        //datosCampos.add(telf);
        datos[5] = telf;
        if (admin.updateDatos(datos, nombreTabla)) {
            JOptionPane.showMessageDialog(null, "Datos Modificados correctamente");
            this.setVisible(false);
            ventanaTabla.actualizar();
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar los Datos del registro o no tiene permisos");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void brnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_brnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
