/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class EditarCiudad extends javax.swing.JFrame {

    public String clave;
    public String nombreTabla;
    public Config_Ciudad ventanaTabla;
    public Administrador admin;
    public ArrayList datosCampos;
    /**
     * Creates new form EditarCiudad
     */
    public EditarCiudad(String clav, String nombreT,Config_Ciudad ventana) {
        initComponents();
        
        admin = new Administrador();
        
        this.clave=clav;
        this.nombreTabla=nombreT;
        this.ventanaTabla=ventana;
        inicializar();
        txtIDCiudad.setEnabled(false);
        this.setTitle("Editar Registro de la Tabla Persona");
        this.setSize(430, 370);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        verificar(); 
        
   }

    private EditarCiudad() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void verificar(){
        if(this.txtIDCiudad.getText().isEmpty()){
            this.setVisible(false);
        }
    }
    public void inicializar(){
        ArrayList datos = new ArrayList<>();
        datos = admin.recuperarDatos(clave,"Ciudades");
        if (datos.isEmpty()){
            JOptionPane.showMessageDialog(null, "No existen datos recuperados");
            //this.setVisible(false);
        }else{
            txtIDCiudad.setText((datos.get(0)).toString());
            txtNombreCiudad.setText((datos.get(1)).toString());
            txtEstado.setText((datos.get(2)).toString());
            txtPais.setText((datos.get(3)).toString());
            txtNumHab.setText((datos.get(4)).toString());
            this.setVisible(true);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDCiudad = new javax.swing.JTextField();
        txtNombreCiudad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumHab = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        brnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Editar Ciudad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 143, 32);

        jLabel2.setText("ID Ciudad:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 68, 90, 14);
        getContentPane().add(txtIDCiudad);
        txtIDCiudad.setBounds(157, 65, 224, 30);
        getContentPane().add(txtNombreCiudad);
        txtNombreCiudad.setBounds(157, 103, 224, 30);

        jLabel3.setText("Nombre Ciudad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 106, 90, 14);

        jLabel4.setText("Estado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 144, 80, 14);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(157, 141, 224, 30);
        getContentPane().add(txtPais);
        txtPais.setBounds(157, 179, 224, 30);

        jLabel5.setText("Pais:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(62, 182, 90, 14);

        jLabel6.setText("Numero Habitantes:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(62, 217, 90, 14);
        getContentPane().add(txtNumHab);
        txtNumHab.setBounds(157, 211, 224, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(119, 295, 91, 23);

        brnCancelar.setText("Cancelar");
        brnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(brnCancelar);
        brnCancelar.setBounds(236, 295, 82, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoFor.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //datosCampos = new ArrayList<>();
        String []datos = new String [5];
        String testNumPisos = txtNumHab.getText();
        int numPisos;
        try{
            numPisos = Integer.parseInt(testNumPisos);
            if(numPisos<0){
                JOptionPane.showMessageDialog(null, "Error al ingresar el numero de habitantes, no negativo");
            }else{
                datos[0]= txtIDCiudad.getText();
                datos[1]= txtNombreCiudad.getText();
                datos[2]= txtEstado.getText();
                datos[3]= txtPais.getText();
                datos[4]= txtNumHab.getText();
                if (admin.updateDatos(datos,nombreTabla)){
                    JOptionPane.showMessageDialog(null, "Datos Modificados correctamente");
                    this.setVisible(false);
                    ventanaTabla.actualizar();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al modificar los Datos del registro o no tiene permisos");
                }
            }
        }catch (Exception e) {
            System.out.println("Debe Ingresar digitos en el Numerde habitantes");
            JOptionPane.showConfirmDialog(null, "Debe Ingresar digitos en el Numerde habitantes");

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void brnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_brnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIDCiudad;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtNumHab;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
