/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import Datos.ConexionBD;
import Datos.MetodosConexion;
import Negocios.Edificios;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Formulario_Edificio extends javax.swing.JFrame {

    public ArrayList datosCampos;
    public Administrador admin;
    /**
     * Creates new form Formulario_Edificio
     */
    public Formulario_Edificio() {
        initComponents();
        
        admin= new Administrador();
        this.setTitle("Crear Registro en Tabla Edificio");
        this.setSize(440, 310);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDEdificio = new javax.swing.JTextField();
        txtNombreEdificio = new javax.swing.JTextField();
        txtDireccionEdificio = new javax.swing.JTextField();
        txtNumPisos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        brnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConfig = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(null);
        getContentPane().add(txtIDEdificio);
        txtIDEdificio.setBounds(173, 65, 230, 30);
        getContentPane().add(txtNombreEdificio);
        txtNombreEdificio.setBounds(173, 103, 230, 30);
        getContentPane().add(txtDireccionEdificio);
        txtDireccionEdificio.setBounds(173, 141, 230, 30);
        getContentPane().add(txtNumPisos);
        txtNumPisos.setBounds(173, 179, 230, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(80, 240, 91, 23);

        brnCancelar.setText("Cancelar");
        brnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(brnCancelar);
        brnCancelar.setBounds(180, 240, 82, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Formulario Edificio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 180, 32);

        jLabel2.setText("ID Edificio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 68, 80, 14);

        jLabel3.setText("Nombre Edificio:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 106, 100, 14);

        jLabel4.setText("Direccion Edificio:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 144, 100, 14);

        jLabel5.setText("Numero de Pisos:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(62, 182, 110, 14);

        btnConfig.setText("Configurar Tabla");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfig);
        btnConfig.setBounds(270, 240, 140, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoFor.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 470, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (admin.pasarDatosEdificio(txtIDEdificio.getText(),txtNombreEdificio.getText(),txtDireccionEdificio.getText(),txtNumPisos.getText())){
            JOptionPane.showMessageDialog(null, "Registro creado con exito en la tabla Edificios");
        }else{
            JOptionPane.showMessageDialog(null, "Error al crear registro en la tabla Edificios o no tiene permisos para esta tabla con el usuario actual");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        Config_Edificio ventana = new Config_Edificio();
        ventana.setVisible(true);
        
        
    }//GEN-LAST:event_btnConfigActionPerformed

    private void brnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_brnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Edificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Edificio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCancelar;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDireccionEdificio;
    private javax.swing.JTextField txtIDEdificio;
    private javax.swing.JTextField txtNombreEdificio;
    private javax.swing.JTextField txtNumPisos;
    // End of variables declaration//GEN-END:variables
}
