/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import Datos.ConexionBD;
import Datos.MetodosConexion;
import Negocios.Personas;
import java.util.ArrayList;
import javax.accessibility.AccessibleAction;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class Formulario_Persona extends javax.swing.JFrame {

    public ArrayList datosCampos;
    public Administrador admin;

    /**
     * Creates new form Formularios
     */
    public Formulario_Persona() {
        admin = new Administrador();
        initComponents();
        
        //this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("Crear Registro en Tabla Persona");
        this.setSize(430, 380);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFechaN = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        brnCancelar = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Formulario Personas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 180, 32);

        jLabel2.setText("ID Persona:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 68, 80, 14);

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 106, 80, 14);

        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(62, 144, 80, 14);

        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(62, 182, 80, 14);

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(62, 217, 90, 14);

        jLabel7.setText("Fecha Nacimiento: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(62, 252, 110, 14);
        getContentPane().add(txtID);
        txtID.setBounds(171, 65, 230, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(171, 103, 230, 30);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(171, 141, 230, 30);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(171, 179, 230, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(171, 211, 230, 30);
        getContentPane().add(txtFechaN);
        txtFechaN.setBounds(171, 249, 230, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(70, 295, 91, 23);

        brnCancelar.setText("Cancelar");
        brnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(brnCancelar);
        brnCancelar.setBounds(179, 295, 82, 23);

        btnConfig.setText("Configurar Tabla");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfig);
        btnConfig.setBounds(279, 295, 120, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoFor.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 440, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (admin.pasarDatosPersona(txtID.getText(),txtNombre.getText(),txtApellido.getText(),txtDireccion.getText(),txtTelefono.getText(),txtFechaN.getText())){
                JOptionPane.showMessageDialog(null, "Registro ingresado con exito en la tabla Personas");
            }else{
                JOptionPane.showMessageDialog(null, "Error al insertar el registro en la tabla Personas o no tiene permisos para esta tabla con el usuario actual");
            }
        } catch (Exception e) {
            System.out.println("Error insertar registro Persona Datos");
            JOptionPane.showConfirmDialog(null, "Error al insertar registro en la tabla Personas");

        }

        /*Personas persona = new Personas();
       persona.setId_persona(txtID.getText());
       persona.setNombre(txtNombre.getText());
       persona.setApellido(txtApellido.getText());
       persona.setDireccion(txtDireccion.getText());
       persona.setF_nacimiento(txtFechaN.getText());
       persona.setTelefono(txtTelefono.getText());
       ConexionBD  conexion = new ConexionBD();
       conexion.conectarBD();
       MetodosConexion metodos = new MetodosConexion();
       metodos.insertar(persona);*/
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void brnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_brnCancelarActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        Config_Persona ventana = new Config_Persona();
        //ventana.setVisible(true);
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCancelar;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
