/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class LogIn extends javax.swing.JFrame {

    public Administrador admin;
    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        admin = new Administrador();
        this.setSize(405, 400);
        this.setResizable(false);
        this.setVisible(true);
        this.setTitle("Log In para la Base de Datos");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 190, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 240, 92, 17);
        getContentPane().add(txtUser);
        txtUser.setBounds(160, 190, 190, 30);
        getContentPane().add(txtPass);
        txtPass.setBounds(160, 240, 190, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 290, 208, 59);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_users.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 30, 160, 150);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logooracle.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 10, 120, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoLOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtUser.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre de Usuario para elingreso a la Base de Datos");
        }else if (txtPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar una contrasena para el ingreso a la base de datos");
        }else{
            System.out.println(txtUser.getText());
            System.out.println(txtPass.getText());
            Object obj;
            obj = admin.cambiarUser(txtUser.getText(), txtPass.getText());
            System.out.println("2" + obj);
            if (obj != null) {
                JOptionPane.showMessageDialog(null, "Ingreso a la Base de Datos Correcta");
                this.setVisible(false);
                Principal ventana = new Principal();
                ventana.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Error al Conectarse a la Base de Datos, nombre o Contrasena incorrecta");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
