/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Negocios.Administrador;
import javax.swing.JOptionPane;
//import static Datos.ConexionBD.login;

/**
 *
 * @author Christian
 */
public class Principal extends javax.swing.JFrame {

    public Administrador admin;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        admin = new Administrador();
        actualizarUser();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setSize(545, 670);
        this.setResizable(false);
        this.setVisible(true);
        btnCrearUsuario.setEnabled(false);
        this.setTitle("Proyecto Base de Datos");
        this.setLocationRelativeTo(null);
        verificarBotones();
    }

    public void actualizarUser() {
        txtUser.setText(admin.conec.getLogin());
        txtPass.setText(admin.conec.getPassword());
    }

    public void verificarBotones() {
        if (admin.conec.getLogin().equals("system")) {
            btnCrearUsuario.setEnabled(true);
            btnPermisos.setEnabled(true);
        } else {
            btnCrearUsuario.setEnabled(false);
            btnPermisos.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnCrearUsuario = new javax.swing.JButton();
        btnEdificio = new javax.swing.JButton();
        btnPersonas = new javax.swing.JButton();
        btnCambiarUser = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCiudad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tituloT.jpg"))); // NOI18N
        jLabel8.setText("Proyecto Base de Datos - Base de Datos Oracle");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, java.awt.Color.gray, java.awt.Color.gray));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 10, 500, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("User:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 570, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 600, 55, 15);

        txtUser.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtUser.setEnabled(false);
        getContentPane().add(txtUser);
        txtUser.setBounds(80, 570, 133, 23);

        txtPass.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtPass.setEnabled(false);
        getContentPane().add(txtPass);
        txtPass.setBounds(80, 600, 133, 21);

        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCrearUser.png"))); // NOI18N
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.setBorderPainted(false);
        btnCrearUsuario.setContentAreaFilled(false);
        btnCrearUsuario.setFocusCycleRoot(true);
        btnCrearUsuario.setFocusTraversalPolicyProvider(true);
        btnCrearUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCrearUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearUsuario);
        btnCrearUsuario.setBounds(20, 240, 120, 110);

        btnEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEdificio.png"))); // NOI18N
        btnEdificio.setText("Tabla Edificios");
        btnEdificio.setBorderPainted(false);
        btnEdificio.setContentAreaFilled(false);
        btnEdificio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdificio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEdificio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdificioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdificio);
        btnEdificio.setBounds(150, 80, 110, 100);

        btnPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnPersona.png"))); // NOI18N
        btnPersonas.setText("Tabla Personas");
        btnPersonas.setBorderPainted(false);
        btnPersonas.setContentAreaFilled(false);
        btnPersonas.setFocusCycleRoot(true);
        btnPersonas.setFocusTraversalPolicyProvider(true);
        btnPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersonas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPersonas);
        btnPersonas.setBounds(20, 80, 120, 100);

        btnCambiarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCambioUser.png"))); // NOI18N
        btnCambiarUser.setText("Cambiar Usuario");
        btnCambiarUser.setContentAreaFilled(false);
        btnCambiarUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambiarUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCambiarUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCambiarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarUser);
        btnCambiarUser.setBounds(130, 250, 130, 97);

        btnPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnPermisos.png"))); // NOI18N
        btnPermisos.setText("Otorgar y Revocar Permisos");
        btnPermisos.setContentAreaFilled(false);
        btnPermisos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPermisos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPermisos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPermisos);
        btnPermisos.setBounds(240, 250, 190, 100);

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnSelect.png"))); // NOI18N
        btnSelect.setText("Consulta Select");
        btnSelect.setContentAreaFilled(false);
        btnSelect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelect.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSelect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect);
        btnSelect.setBounds(20, 430, 120, 100);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnExit.setText("Salir");
        btnExit.setContentAreaFilled(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(480, 580, 60, 60);

        btnCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCiudades.png"))); // NOI18N
        btnCiudad.setText("Tabla Ciudades");
        btnCiudad.setContentAreaFilled(false);
        btnCiudad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCiudad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCiudad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(btnCiudad);
        btnCiudad.setBounds(260, 70, 120, 110);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nota: Al entrar en una tabla puede Crear, Modificar y Eliminar registros de la misma.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 190, 510, 15);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros (Agregar, Modificar, Eliminar)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 50, 520, 170);

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta Select", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 400, 520, 140);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 540, 220, 100);

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Nota: Solo el usuario \"system\" puede crear otros usuarios, otorgar y revocar permisos.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 360, 510, 15);

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario (Creacion y Permisos)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 520, 170);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo6.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-6, 0, 550, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // TODO add your handling code here:
        CrearUser ventanaUsuario = new CrearUser();
        ventanaUsuario.setVisible(true);
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdificioActionPerformed
        // TODO add your handling code here:
        Formulario_Edificio ventanaEdificio = new Formulario_Edificio();
        ventanaEdificio.setVisible(true);
    }//GEN-LAST:event_btnEdificioActionPerformed

    private void btnPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonasActionPerformed
        // TODO add your handling code here:
        Formulario_Persona ventanaPersona = new Formulario_Persona();
        ventanaPersona.setVisible(true);
    }//GEN-LAST:event_btnPersonasActionPerformed

    private void btnCambiarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarUserActionPerformed
        // TODO add your handling code here:
        CambiarUser ventanaCambiar = new CambiarUser(this);
        ventanaCambiar.setVisible(true);
        //actualizarUser();
        //this.repaint();
    }//GEN-LAST:event_btnCambiarUserActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        // TODO add your handling code here:
        VentanaPermisos ventana = new VentanaPermisos();
        //ventana.setVisible(true);
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        VentanaSelect ventana = new VentanaSelect();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Object[] opciones = {"Aceptar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane, "Desea salir del Programa", "Mensaje de Confirmacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar");
        if (eleccion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiudadActionPerformed
        // TODO add your handling code here:
        Formulario_Ciudad ventanaCiudad = new Formulario_Ciudad();
        ventanaCiudad.setVisible(true);
    }//GEN-LAST:event_btnCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarUser;
    private javax.swing.JButton btnCiudad;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEdificio;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnPersonas;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
